FROM node:18-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install --production

COPY . .

FROM node:18-alpine

WORKDIR /app

# Create non-root user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY --from=builder /app /app

USER appuser

EXPOSE 3000

CMD ["node", "app.js"]